### PR TITLE
Hash backup

### LINKED ISSUE #106: Improve backup infrastructure
Right now we are using custom back up scripts to perform backups. We should instead look into using backup solutions like [rsnapshot](http://rsnapshot.org/rsnapshot/docs/docbook/rest.html#backup-script) and [HashBackup](http://www.hashbackup.com/).

### PR DESCRIPTION
**Pull request by yatharthranjan**
Add hash backup for more unified backups
Closes #106

### CODE REVIEW

**Comment by afolarin** [comment]
Some good suggestions cheers @imgrant :+1

**Comment by yatharthranjan** [comment]
Hi @imgrant, Thanks for the input. It is very useful. Please see below -
- 1 and 2 - Good point. I missed those. Will add them.
- 3 - The backup info is written in the logs since this is supposed to be run in the background. We can certainly specify this in the README
- 4 - We can certainly have `selftest` on a different schedule but that would mean having a separate systemd timer. Since we have also specified Incremental checking, for example,` --inc 1d/30d`, this `means that selftest is run every day, perhaps via a cron job, and the entire backup should be checked over a 30-day period.  Each day, 1/30th of the backup is checked.`
- 5 and 6 - Right now we are just configuring the hashbackups for small size data like databases, configuration files, other important files and not for historic data currently.  So that why i did not consider these much, but indeed these should be set configurable via the `backup.conf` file.
- 7 - According to the documentation, `The compatibility goal is that backups created less than a year ago should be accessible with the latest version.` and our retain config is exactly 1 year (if we upgrade hb within one year), then we should be okay. But it worth listing this in the README as well.
- 8 - Yes good catch. We totally missed this. Although we don't have any identifiable data in there so maybe we will be fine. what do you think @afolarin ??
- 9 - The passphrase will be asked or taken from the env var `HBPASS` whenever access to the backup is requested. It is similar to the way we ssh in to rosaling with a key and a passphrase. additional details here - http://www.hashbackup.com/technical/security 

Quoting from the page above - 
```
   d. a passphrase can be added to the key with the -p option.  -p ask
   (add "ask" after -p) means to read the passphrase from the keyboard
   on every HB command.  A passphrase secures backup data: - for users
   in hosted or managed environments, like a VPS - when the backup
   directory is on USB thumb drives - when the backup directory is on
   mounted storage like Google Drive, Amazon Cloud Drive, Dropbox,
   etc.

   e. the -p env (add "env" after -p) option means HB will read the
   passphrase from the environment variable HBPASS.  This is more
   convenient than -k ask, because the user can set the environment
   variable once in their login session.  But it is less secure
   because any program the user runs also can read the passphrase.
   Users can add a command to their .profile startup file to set the
   environment variable, but this is potentially less secure and not
   recommended unless the user's home directory is encrypted by the
   OS.  The protection on .profile should be set to 0400 (user read,
   group none, others none).
```

Hope this makes sense. Please correct me if/ wherever I am wrong (Since a newbie for hashbackup). Thanks

**Comment by speelen** [comment]
Regarding 8. If there are identifiers stored that could lead to a person, e.g. via a reference list someone has, then the GDPR applies. Only if there is NO WAY to identify a person in that case the GDPR does not apply.

**Comment by imgrant** [comment]
@yatharthranjan Okay, re 5 & 6 given you're currently only focusing on smaller backups, the following point concerning `selftest` (4 above) also does not yet apply, but worth noting for when you might need to scale up this backup process: you should watch out for the situation where your selftest schedule cannot successfully complete, e.g. checking 1/30th every day is okay when 1/30th is a few hundred megabytes, but when 1/30th is many gigabytes, it may not be computationally possible to complete the checking.

Re point 7 -- your statement is fine for restore (and indeed, I think it may well be possible to restore older backups, i.e. the author's aim of guaranteeing backups up to one year old is a worst-case scenario), but I was referring to the beta expiry of hashbackup; as it says on the download page:
> Beta versions of HashBackup expire quarterly on the 15th of January, April, July, and October.  Use hb upgrade to get the latest version and extend the expiration date.  
IMPORTANT: You can always access your backup data after the expiration date: everything continues to work except the backup command. 
i.e. you need to do `hb upgrade` at least every quarter in order to be able to actually do backups!

@yatharthranjan @speelen regarding point 8, GDPR, I only meant to flag this in terms of, I hope the hashbackup author doesn't go so far as to actually block download/usage in the EU (for beta or any eventual production release). I cannot really see how software like hashbackup can or can't be GDPR 'compliant', whatever that actually means. It's the responsibility of the data processor and/or data controller to be GDPR compliant, and so it's up to you to control, e.g., data retention or identifiable data in hashbackup archives in the case of right to be forgotten, privacy policies, etc. At least, that's my understanding.
Obviously, different software might hinder or ease that process for you. In the case of hashbackup, you can use the `rm` operation to remove specific files, all versions, from your backups, and, of course encryption helps you in the case of data breaches or leaks from your backups.

**Comment by yatharthranjan** [comment]
Yes i have made most of the options configurable now so can be easily repurposed for large data sets in the future.

Re point 7, okay i see. I will add this to the README to add this as a cron job every week or so. Or we can have a separate systemd timer for selftests and upgrade.

I think we should be okay for GDPR. In any case we need to backup pseudonymised data and this is one of the best solutions out there. All backups are encrypted and protected with a passphrase. I don't know what more we can do to be more compliant with GDPR.

**Comment by afolarin** [comment]
> 4 - We can certainly have selftest on a different schedule but that would mean having a separate systemd timer. Since we have also specified Incremental checking, for example,--inc 1d/30d, this means that selftest is run every day, perhaps via a cron job, and the entire backup should be checked over a 30-day period. Each day, 1/30th of the backup is checked.
We could also just have some logic so that the check runs every 7th or 30th backup? That way you don't have to add a parallel cron job

**Comment by yatharthranjan** [comment]
Hi all, Thanks for the inputs.

I have pushed the changes according to the comments. 

The selftest now run every day and 1/120th of the backup is checked (so the whole self test will be completed over a period of 120 days) and also added `sample` option which takes 4 random samples from the arc file instead of downloading the whole file. I think this should work well with large backups now.

**Comment by speelen** [comment]
@imgrant, you are right. Being GDR compliant is the responsibility of the data controller. But by the fact that we are already using hb, means that it IS available to EU users. So we should be good I think.

**Pull request merged**
