### PR TITLE
Kafka configuration updates

### PR DESCRIPTION
**Pull request by blootsvoets**
- Add all zookeeper hosts to `zookeeper.connect` settings
- Use lz4 compression by default (see http://blog.yaorenjie.com/2017/01/03/Kafka-0-10-Compression-Benchmark/, lz4 is the most efficient and still space-saving algorithm)
- Explicitly set the Kafka message version, for safe rolling upgrades
- Fix install-script with zsh

### CODE REVIEW

**Comment by yatharthranjan** [comment]
Will this update be compatible with current kafka deployment ?

**Comment by blootsvoets** [comment]
yes, indeed, Confluent version 4.1.0 is already using message format 1.1, see https://docs.confluent.io/current/installation/upgrade.html#upgrade-all-kafka-brokers. It's a reminder to set these properties on the next upgrade.

**Comment by blootsvoets** [comment]
Btw, I don't think that these properties are propagated unless running `docker-compose up` again for the individual containers (doing a recreate).

**Comment by yatharthranjan** [comment]
Yeah i know. But to enable compression we will need to recreate them. Or at least edit server.properties inside each container and do a rolling restart. 
But I am wondering will the compression work with the current state of data in kafka ? Since there is a lot of data already present in Kafka. Although it does say that messages are compressed and decompressed at producer and consumer level and consumers receive a mix of compressed and uncompressed msgs, so maybe it will be fine ?

**Comment by blootsvoets** [comment]
The compression setting in this pull request will not affect existing topics or data. It only changes the topics if you restart the server/volumes from scratch. I haven't found an example of people changing the compression on an existing topic.

**Comment by yatharthranjan** [comment]
Okay yes it does say that it is backward compatible as well. Just wondering because we already have like 500gb of kafka logs. Anyways will enable the compression now. Thanks

**Comment by blootsvoets** [comment]
Looking it up, indeed it affects only new messages if actually applied to an existing topic. You could run an update of `kafka-init` to alter existing topics as well, e.g.
```
kafka-configs --alter --entity-name example --entity-type topics --zookeeper zookeeper-1:2181 --add-config compression.type=lz4
```

**Comment by yatharthranjan** [comment]
Okay thanks. One more question, do we also have to enable compression at producer level ? Like for example rest proxy ?

**Comment by blootsvoets** [comment]
Good point. It's not mandatory, but for the REST proxy it definitely makes sense.

**Pull request merged**
