### PR TITLE
Merge latest changes to master

### PR DESCRIPTION
**Pull request by nivemaham**
Merge latest changes to master

### CODE REVIEW

**Comment by baixiac** [comment]
Should this RADAR-Schemas [issue](https://github.com/RADAR-base/RADAR-Schemas/issues/272) be addressed before the merging/release?

**Comment by nivemaham** [comment]
@baixiac I think that would be ideal. But would you have time to look into it? Unfortunately, I don't.

**Comment by baixiac** [comment]
Hi, @nivemaham. The issue has been resolved and merged to `dev`. Thanks and this PR is now unblocked.

**Review by yatharthranjan — APPROVED** [review]
LGTM

**Review by baixiac — APPROVED** [review]

**Comment by nivemaham** [comment]
Thank you. I will proceed with the merge

**Pull request merged**
